### ISSUE TITLE
Set Up failed

### ISSUE THREAD

**Issue by yanlinaung30** [comquas/Lue#1]
What additional steps required in Set Up?
I have encountered the following error.

ubuntu@ubuntu-xenial:~/Repositories/Lue$ php artisan migrate
PHP Warning:  require(/home/ubuntu/Repositories/Lue/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /home/ubuntu/Repositories/Lue/bootstrap/autoload.php on line 17
PHP Fatal error:  require(): Failed opening required '/home/ubuntu/Repositories/Lue/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/php') in /home/ubuntu/Repositories/Lue/bootstrap/autoload.php on line 17

**Comment by saturngod** [comment]
Oh! forget to mention about composer. Laravel project need to run composer install
```
$ composer install
```

**Comment by yanlinaung30** [comment]
Thanks for your quick reply.
Set Up OK!
